### ISSUE TITLE
Missing space after `data-require-auth` attribute

### ISSUE THREAD

**Issue by piotrminkina** [intergral/mkdocs-gitlab-review-plugin#1]
Hello,

I noticed missing space at file [mkdocs_gitlab_review/plugin.py](https://github.com/intergral/mkdocs-gitlab-review-plugin/blob/a75cb21506157c476a06228fc98eb0b3ffbcdd0a/mkdocs_gitlab_review/plugin.py) on line [41](https://github.com/intergral/mkdocs-gitlab-review-plugin/blob/a75cb21506157c476a06228fc98eb0b3ffbcdd0a/mkdocs_gitlab_review/plugin.py#L41).

Actual:
```python
               "%s" \
```
Expected:
```python
               "%s " \
```

Due to the absence of this space, the generated HTML attributes are clumped together, as follows:
```html
data-merge-request-id='10' data-require-auth='true'data-mr-url='https://example.com' id='review-app-toolbar-script'
```

Regards
Piotr Minkina

**Comment by Flambe** [comment]
Fixed, thanks for the report!
